---
title: '[CLIENT NAME] Analytics Performance'
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float:
      collapse: true
      smooth_scroll: false
    fig_width: 8
    fig_height: 7
    fig_align: "center"
    df_print: tibble
    theme: sandstone
---

```{r setup, include=FALSE}

# Libraries
library(googleAnalyticsR)
library(lubridate)
library(ggplot2)
library(tidyverse)
library(plotly)
library(rmarkdown)
library(knitr)
library(scales)

# Variables
clientId <- Sys.getenv("APICLIENTID")
clientSecret <- Sys.getenv("APICLIENTSECRET")
options(googleAuthR.client_id = clientId)
options(googleAuthR.client_secret = clientSecret)
options(googleAuthR.scopes.selected = "https://www.googleapis.com/auth/analytics")
ga_auth()
viewId <- Sys.getenv("CLIENT1VIEWID")

# Dates
yesterday = today() - days(1)
startOfCurrentMonth = today() - day(today()) + 1
endOfLastMonth = startOfCurrentMonth - 1 
starOfLastMonth = endOfLastMonth - days_in_month(endOfLastMonth) + 1
thirtyDaysAgo <- today() - days(30)
sixtyDaysAgo <- today() - days(60)
ninetyDaysAgo <- today() - days(90)
aYearAgo <- today() - days(365)

```

# Overview of yesterday's metrics

```{r yesterday overview, message=FALSE, echo=FALSE, eval=FALSE}

yesterdayOverview <- google_analytics(viewId, date_range = c(thirtyDaysAgo, yesterday), 
                   metrics = c('sessions','users','sessionsPerUser','pageviewsPerSession','avgSessionDuration',
                               'bounceRate','transactions','transactionRevenue','revenuePerTransaction','transactionsPerSession'),
                   dimensions = 'date')

names(yesterdayOverview) <- c('Date','Sessions','Users','SessionsPerUser','PagesPerSession',
                              'AvgSessionDuratio','BounceRate','Transactions','Revenue','AvgOrderValue','ConversionRate')

longYesterdayOverview <- yesterdayOverview %>% gather(metric, value, Sessions:ConversionRate)

ggplot(longYesterdayOverview, aes(x = Date, y = value)) +
    geom_line() +
    facet_grid(metric~., scales = "free_y")

```

# New vs Returning

```{r new vs returning, message=FALSE, echo=FALSE, eval=FALSE}

newVsReturning <- google_analytics(viewId, date_range = c(thirtyDaysAgo, yesterday), 
                   metrics = 'users',
                   dimensions = c('date','userType'))

names(newVsReturning) <- c('Date','userType','Users')

ggplot(newVsReturning) +
    geom_area(aes(x = Date, y = Users, fill = userType), position = "stack") +
    theme(legend.position = "bottom")

```

# Hostnames

```{r hostnames, message=FALSE, echo=FALSE, eval=FALSE}

hostnames <- google_analytics(viewId, date_range = c(thirtyDaysAgo, yesterday), 
                   metrics = 'sessions',
                   dimensions = 'hostname')

kable(hostnames %>% arrange(desc(sessions)))

```

# Device Category

```{r device category, message=FALSE, echo=FALSE, eval=FALSE}

deviceCategory <- google_analytics(viewId, date_range = c(thirtyDaysAgo, yesterday), 
                   metrics = 'sessions',
                   dimensions = c('date','deviceCategory'))

names(deviceCategory) <- c('Date','deviceCategory','Sessions')

ggplot(deviceCategory) +
    geom_area(aes(x = Date, y = Sessions, fill = deviceCategory), position = "stack") +
    theme(legend.position = "bottom")

```

# Channel Performance

```{r channel performance, echo=FALSE, message=FALSE, eval=FALSE}

channelPerformance <- google_analytics(viewId, date_range = c(thirtyDaysAgo, yesterday), 
                   metrics = c('transactionRevenue','revenuePerTransaction','transactionsPerSession'),
                   dimensions = 'channelGrouping')

plot_ly(data = channelPerformance, x = ~transactionsPerSession, y = ~revenuePerTransaction, size = ~transactionRevenue,
        text = ~paste("Channel: ", channelGrouping, "<br>Revenue: ", transactionRevenue,
                      "<br>AvgOrderValue: ", revenuePerTransaction, "<br>ConversionRate: ", transactionsPerSession))

```

# Pages Performance

```{r pages performance, echo=FALSE, message=FALSE, eval=FALSE}

pagesPerformance <- google_analytics(viewId, date_range = c(thirtyDaysAgo, yesterday), 
                   metrics = c('pageviews','avgTimeOnPage','pageValue'),
                   dimensions = 'pagePath')

plot_ly(data = pagesPerformance, x = ~log(avgTimeOnPage), y = ~log(pageValue), size = ~pageviews,
        text = ~paste("Page: ", pagePath, "<br>Pageviews: ", pageviews,
                      "<br>AvgTimeOnPage: ", avgTimeOnPage, "<br>PageValue: ", pageValue))

```

# Landing Pages Performance

```{r landing pages performance, echo=FALSE, message=FALSE, eval=FALSE}

landingPagesPerformance <- google_analytics(viewId, date_range = c(thirtyDaysAgo, yesterday), 
                   metrics = c('sessions','avgSessionDuration','transactionsPerSession'),
                   dimensions = 'landingPagePath')

plot_ly(data = landingPagesPerformance, x = ~log(avgSessionDuration), y = ~log(transactionsPerSession), size = ~sessions,
        text = ~paste("LandingPage: ", landingPagePath, "<br>Sessions: ", sessions,
                      "<br>AvgSessionDuration: ", avgSessionDuration, "<br>ConversionRate: ", transactionsPerSession))

```

# E-commerce Performance

```{r ecommerce performance, echo=FALSE, message=FALSE, eval=FALSE}

ecommerceOverview <- google_analytics(viewId, date_range = c(thirtyDaysAgo, yesterday), 
                                      metrics = c('transactions','transactionsPerSession','transactionRevenue',
                                                  'revenuePerTransaction'),
                                      dimensions = 'date')

names(ecommerceOverview) <- c('Date','Transactions','ConversionRate','Revenue','AvgOrderValue')

longEcommerceOverview <- ecommerceOverview %>% gather(metric, value, Transactions:AvgOrderValue)

ggplot(longEcommerceOverview, aes(x = Date, y = value)) +
    geom_line() +
    facet_grid(metric~., scales = "free_y")

```

# Session Count

```{r count of sessions, echo=FALSE, message=FALSE, eval=FALSE}

sessionCount <- google_analytics(viewId, date_range = c(thirtyDaysAgo, yesterday), 
                                 metrics = c('users','pageviews'),
                                 dimensions = 'sessionCount')

sessionCount$sessionCount <- as.numeric(sessionCount$sessionCount)
sessionCount$bucket <- NA

sessionCount[sessionCount$sessionCount == 1,"bucket"] <- '1'
sessionCount[sessionCount$sessionCount == 2,"bucket"] <- '2'
sessionCount[sessionCount$sessionCount == 3,"bucket"] <- '3'
sessionCount[sessionCount$sessionCount == 4,"bucket"] <- '4'
sessionCount[sessionCount$sessionCount == 5,"bucket"] <- '5'
sessionCount[sessionCount$sessionCount == 6,"bucket"] <- '6'
sessionCount[sessionCount$sessionCount == 7,"bucket"] <- '7'
sessionCount[sessionCount$sessionCount == 8,"bucket"] <- '8'
sessionCount[sessionCount$sessionCount == 9,"bucket"] <- '9'
sessionCount[sessionCount$sessionCount > 9 & sessionCount$sessionCount < 26,"bucket"] <- '10 - 25' 
sessionCount[sessionCount$sessionCount > 25 & sessionCount$sessionCount < 51,"bucket"] <- '26 - 50' 
sessionCount[sessionCount$sessionCount > 50 & sessionCount$sessionCount < 101,"bucket"] <- '51 - 100' 
sessionCount[sessionCount$sessionCount > 100,"bucket"] <- '> 100' 

sessionCountGrouped <- sessionCount %>% group_by(bucket) %>% summarize(Users = sum(users), Pageviews = sum(pageviews)) %>%
    gather(metric, value, Users:Pageviews)

sessionCountGrouped$bucket <- factor(sessionCountGrouped$bucket, levels = c('1','2','3','4','5','6','7','8','9','10 - 25','26 - 50','51 - 100','> 100'))

ggplot(sessionCountGrouped, aes(x = bucket, y = value, fill = metric)) +
    geom_col(position='dodge') +
    scale_y_continuous(labels=comma) +
    coord_flip() 

```

# Days Since Last Session

```{r days since last session, echo=FALSE, message=FALSE, eval=FALSE}

daysSinceLastSession <- google_analytics(viewId, date_range = c(thirtyDaysAgo, yesterday), 
                                 metrics = c('users','pageviews','sessions'),
                                 dimensions = 'daysSinceLastSession')

daysSinceLastSession$daysSinceLastSession <- as.numeric(daysSinceLastSession$daysSinceLastSession)
daysSinceLastSession$bucket <- NA

daysSinceLastSession[daysSinceLastSession$daysSinceLastSession == 0,"bucket"] <- '0'
daysSinceLastSession[daysSinceLastSession$daysSinceLastSession == 1,"bucket"] <- '1'
daysSinceLastSession[daysSinceLastSession$daysSinceLastSession == 2,"bucket"] <- '2'
daysSinceLastSession[daysSinceLastSession$daysSinceLastSession == 3,"bucket"] <- '3'
daysSinceLastSession[daysSinceLastSession$daysSinceLastSession == 4,"bucket"] <- '4'
daysSinceLastSession[daysSinceLastSession$daysSinceLastSession == 5,"bucket"] <- '5'
daysSinceLastSession[daysSinceLastSession$daysSinceLastSession == 6,"bucket"] <- '6'
daysSinceLastSession[daysSinceLastSession$daysSinceLastSession == 7,"bucket"] <- '7'
daysSinceLastSession[daysSinceLastSession$daysSinceLastSession == 8,"bucket"] <- '8'
daysSinceLastSession[daysSinceLastSession$daysSinceLastSession == 9,"bucket"] <- '9'
daysSinceLastSession[daysSinceLastSession$daysSinceLastSession > 9 & daysSinceLastSession$daysSinceLastSession < 26,"bucket"] <- '10 - 25' 
daysSinceLastSession[daysSinceLastSession$daysSinceLastSession > 25 & daysSinceLastSession$daysSinceLastSession < 51,"bucket"] <- '26 - 50' 
daysSinceLastSession[daysSinceLastSession$daysSinceLastSession > 50 & daysSinceLastSession$daysSinceLastSession < 101,"bucket"] <- '51 - 100' 
daysSinceLastSession[daysSinceLastSession$daysSinceLastSession > 100,"bucket"] <- '> 100' 

daysSinceLastSessionGrouped <- daysSinceLastSession %>% group_by(bucket) %>%
    summarize(Users = sum(users), Pageviews = sum(pageviews), Sessions = sum(sessions)) %>%
    gather(metric, value, Users:Sessions)

daysSinceLastSessionGrouped$bucket <- factor(daysSinceLastSessionGrouped$bucket,
                                             levels = c('0','1','2','3','4','5','6','7','8','9','10 - 25','26 - 50','51 - 100','> 100'))

ggplot(daysSinceLastSessionGrouped, aes(x = bucket, y = value, fill = metric)) +
    geom_col(position='dodge') +
    scale_y_continuous(labels=comma) +
    coord_flip() 

```

# Session Duration

```{r session duration, echo=FALSE, message=FALSE, eval=FALSE}

sessionDuration <- google_analytics(viewId, date_range = c(thirtyDaysAgo, yesterday), 
                                 metrics = c('users','pageviews','sessions'),
                                 dimensions = 'sessionDurationBucket')

sessionDuration$sessionDurationBucket <- as.numeric(sessionDuration$sessionDurationBucket)
sessionDuration$bucket <- NA

sessionDuration[sessionDuration$sessionDurationBucket < 11,"bucket"] <- '0 - 10' 
sessionDuration[sessionDuration$sessionDurationBucket > 10 & sessionDuration$sessionDurationBucket < 31,"bucket"] <- '11 - 30' 
sessionDuration[sessionDuration$sessionDurationBucket > 30 & sessionDuration$sessionDurationBucket < 61,"bucket"] <- '31 - 60' 
sessionDuration[sessionDuration$sessionDurationBucket > 60 & sessionDuration$sessionDurationBucket < 181,"bucket"] <- '61 - 180' 
sessionDuration[sessionDuration$sessionDurationBucket > 180 & sessionDuration$sessionDurationBucket < 601,"bucket"] <- '181 - 600' 
sessionDuration[sessionDuration$sessionDurationBucket > 600 & sessionDuration$sessionDurationBucket < 1801,"bucket"] <- '601 - 1800' 
sessionDuration[sessionDuration$sessionDurationBucket > 1800,"bucket"] <- '> 1800' 

sessionDurationGrouped <- sessionDuration %>% group_by(bucket) %>%
    summarize(Users = sum(users), Pageviews = sum(pageviews), Sessions = sum(sessions)) %>%
    gather(metric, value, Users:Sessions)

sessionDurationGrouped$bucket <- factor(sessionDurationGrouped$bucket,
                                             levels = c('0 - 10','11 - 30','31 - 60','61 - 180','181 - 600','601 - 1800','> 1800'))

ggplot(sessionDurationGrouped, aes(x = bucket, y = value, fill = metric)) +
    geom_col(position='dodge') +
    scale_y_continuous(labels=comma) +
    coord_flip() 

```

# Page Depth

```{r page depth, echo=FALSE, message=FALSE, eval=FALSE}

pageDepth <- google_analytics(viewId, date_range = c(thirtyDaysAgo, yesterday), 
                                 metrics = c('users','pageviews','sessions'),
                                 dimensions = 'pageDepth')

pageDepth$pageDepth <- as.numeric(pageDepth$pageDepth)
pageDepth$bucket <- NA

pageDepth[pageDepth$pageDepth == 0,"bucket"] <- '0' 
pageDepth[pageDepth$pageDepth == 1,"bucket"] <- '1' 
pageDepth[pageDepth$pageDepth == 2,"bucket"] <- '2' 
pageDepth[pageDepth$pageDepth == 3,"bucket"] <- '3' 
pageDepth[pageDepth$pageDepth == 4,"bucket"] <- '4' 
pageDepth[pageDepth$pageDepth == 5,"bucket"] <- '5' 
pageDepth[pageDepth$pageDepth == 6,"bucket"] <- '6' 
pageDepth[pageDepth$pageDepth == 7,"bucket"] <- '7' 
pageDepth[pageDepth$pageDepth == 8,"bucket"] <- '8' 
pageDepth[pageDepth$pageDepth == 9,"bucket"] <- '9' 
pageDepth[pageDepth$pageDepth == 10,"bucket"] <- '10' 
pageDepth[pageDepth$pageDepth == 11,"bucket"] <- '11' 
pageDepth[pageDepth$pageDepth == 12,"bucket"] <- '12' 
pageDepth[pageDepth$pageDepth == 13,"bucket"] <- '13' 
pageDepth[pageDepth$pageDepth == 14,"bucket"] <- '14' 
pageDepth[pageDepth$pageDepth == 15,"bucket"] <- '15' 
pageDepth[pageDepth$pageDepth == 16,"bucket"] <- '16' 
pageDepth[pageDepth$pageDepth == 17,"bucket"] <- '17' 
pageDepth[pageDepth$pageDepth == 18,"bucket"] <- '18' 
pageDepth[pageDepth$pageDepth == 19,"bucket"] <- '19' 
pageDepth[pageDepth$pageDepth == 20,"bucket"] <- '20' 
pageDepth[pageDepth$pageDepth > 20,"bucket"] <- '> 20' 

pageDepthGrouped <- pageDepth %>% group_by(bucket) %>%
    summarize(Users = sum(users), Pageviews = sum(pageviews), Sessions = sum(sessions)) %>%
    gather(metric, value, Users:Sessions)

pageDepthGrouped$bucket <- factor(pageDepthGrouped$bucket,
                                  levels = c('0','1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
                                             '11', '12', '13', '14', '15', '16', '17', '18', '19', '20','> 20'))

ggplot(pageDepthGrouped, aes(x = bucket, y = value, fill = metric)) +
    geom_col(position='dodge') +
    scale_y_continuous(labels=comma) +
    coord_flip() 

```

# Correlation plot

```{r correlation plot, echo=FALSE, message=FALSE, eval=FALSE}

library(corrplot)

correlationData <- google_analytics(viewId, date_range = c(aYearAgo, yesterday), 
                   metrics = c('sessions','users','sessionsPerUser','pageviewsPerSession','avgSessionDuration',
                               'bounceRate','transactions','transactionRevenue','revenuePerTransaction','transactionsPerSession'),
                   dimensions = 'date')

names(correlationData) <- c('Date','Sessions','Users','SessionsPerUser','PagesPerSession',
                              'AvgSessionDuration','BounceRate','Transactions','Revenue','AvgOrderValue','ConversionRate')

corr <- cor(correlationData[,-1])

corrplot(corr, method = "pie", type = "upper")


```

# City performance {.tabset}

```{r city performance, echo=FALSE, message=FALSE, warning=FALSE, results='asis', eval=FALSE}

library(ggmap)

cityPerformance <- google_analytics(viewId, date_range = c(thirtyDaysAgo, yesterday),
                   metrics = c('pageviews','sessions','bounceRate','pageviewsPerSession','transactionRevenue','transactionsPerSession'),
                   dimensions = c('city','longitude','latitude'))

cityPerformance$latitude <- as.numeric(cityPerformance$latitude)
cityPerformance$longitude <- as.numeric(cityPerformance$longitude)

ireland <- get_map('Athlone', zoom=7)

cat('\n\n## Pageviews\n')
ggmap(ireland) + geom_point(data = cityPerformance, aes(x = longitude, y = latitude, size = pageviews),
                            color = 'blue', alpha = 0.5) +
    theme(legend.position = "bottom") +
    scale_size_continuous(labels=comma)

cat('\n\n## Sessions\n')
ggmap(ireland) + geom_point(data = cityPerformance, aes(x = longitude, y = latitude, size = sessions),
                            color = 'blue', alpha = 0.5) +
    theme(legend.position = "bottom") +
    scale_size_continuous(labels=comma)

cat('\n\n## Bounce Rate\n')
ggmap(ireland) + geom_point(data = cityPerformance, aes(x = longitude, y = latitude, size = bounceRate),
                            color = 'blue', alpha = 0.5) +
    theme(legend.position = "bottom") +
    scale_size_continuous(labels=comma)

cat('\n\n## Pages/Session\n')
ggmap(ireland) + geom_point(data = cityPerformance, aes(x = longitude, y = latitude, size = pageviewsPerSession),
                            color = 'blue', alpha = 0.5) +
    theme(legend.position = "bottom") +
    scale_size_continuous(labels=comma)

cat('\n\n## Revenue\n')
ggmap(ireland) + geom_point(data = cityPerformance, aes(x = longitude, y = latitude, size = transactionRevenue),
                            color = 'blue', alpha = 0.5) +
    theme(legend.position = "bottom") +
    scale_size_continuous(labels=comma)

cat('\n\n## Conversion Rate\n')
ggmap(ireland) + geom_point(data = cityPerformance, aes(x = longitude, y = latitude, size = transactionsPerSession),
                            color = 'blue', alpha = 0.5) +
    theme(legend.position = "bottom") +
    scale_size_continuous(labels=comma)

```

# Events {.tabset}

```{r event performance, echo=FALSE, results='asis', message=FALSE, eval=FALSE}

eventPerformance <- google_analytics(viewId, date_range = c(thirtyDaysAgo, yesterday),
                   metrics = c('totalEvents','sessionsWithEvent'),
                   dimensions = c('date','eventCategory'))

cat('\n\n## Total Events\n')
ggplot(eventPerformance, aes(x = date, y = totalEvents, color = eventCategory)) + geom_line()

cat('\n\n## Sessions With Events\n')
ggplot(eventPerformance, aes(x = date, y = sessionsWithEvent, color = eventCategory)) + geom_line()

```

# Goal performance {.tabset}

```{r goal performance, echo=FALSE, message=FALSE, results='asis', eval=FALSE}

goalPerformance <- google_analytics(viewId, date_range = c(thirtyDaysAgo, yesterday),
                   metrics = c('goal1Completions','goal2Completions','goal1ConversionRate','goal2ConversionRate'),
                   dimensions = 'date')

goalCompletions <- goalPerformance %>% gather(goal, completions, 2:3)
goalConversionRate <- goalPerformance %>% gather(goal, conversionRates, 4:5)

cat('\n\n## Completions\n')
ggplot(goalCompletions, aes(x = date, y = completions, color = goal)) + geom_line()

cat('\n\n## Conversion Rates\n')
ggplot(goalConversionRate, aes(x = date, y = conversionRates, color = goal)) + geom_line()

```
