---
title: "[CLIENT NAME] AdWords Performance"
output:
  html_document:
    toc: true
    toc_depth: 2
    number_sections: true
---

```{r setup, include=FALSE}
# Libraries
library(RAdwords)
library(lubridate)
library(ggplot2)
library(tidyverse)
library(corrplot)
library(scales)

# Variables
googleAuth <- doAuth()
customerId <- Sys.getenv("CLIENT1ID")

# Dates
yesterday = today() - days(1)
startOfCurrentMonth = today() - day(today()) + 1
endOfLastMonth = startOfCurrentMonth - 1 
starOfLastMonth = endOfLastMonth - days_in_month(endOfLastMonth) + 1
```
# Campaign performance
## Performance: Month-to-date

```{r campaign scatterplot 1, echo=FALSE, eval=FALSE}

chunk1_body <- statement(select=c('CampaignName','Conversions','CostPerConversion','Cost'),
                         report="CAMPAIGN_PERFORMANCE_REPORT",
                         where="Cost > 150000000",
                         start=startOfCurrentMonth,
                         end=yesterday)

chunk1_data <- getData(clientCustomerId=customerId, google_auth=googleAuth, statement=chunk1_body)

names(chunk1_data) <- c("Campaign", "Conversions", "CPA", "Cost")

ggplot(chunk1_data, aes(x = Cost, y = CPA, size = Conversions)) +
    geom_point() +
    geom_text(aes(label = Campaign))

```

## Performance: Last 30 days

```{r campaign scatterplot 2, echo=FALSE, eval=FALSE}

thirtyDaysAgo <- today() - days(30)

chunk2_body <- statement(select=c('CampaignName','Conversions','CostPerConversion','Cost'),
                         report="CAMPAIGN_PERFORMANCE_REPORT",
                         where="Cost > 150000000",
                         start=thirtyDaysAgo,
                         end=yesterday)

chunk2_data <- getData(clientCustomerId=customerId, google_auth=googleAuth, statement=chunk2_body)

names(chunk2_data) <- c("Campaign", "Conversions", "CPA", "Cost")

ggplot(chunk2_data, aes(x = Cost, y = CPA, size = Conversions)) +
    geom_point() +
    geom_text(aes(label = Campaign))

```

## Performance: Last 60 days

```{r campaign scatterplot 3, echo=FALSE, eval=FALSE}

sixtyDaysAgo <- today() - days(60)

chunk3_body <- statement(select=c('CampaignName','Conversions','CostPerConversion','Cost'),
                         report="CAMPAIGN_PERFORMANCE_REPORT",
                         where="Cost > 150000000",
                         start=sixtyDaysAgo,
                         end=yesterday)

chunk3_data <- getData(clientCustomerId=customerId, google_auth=googleAuth, statement=chunk3_body)

names(chunk3_data) <- c("Campaign", "Conversions", "CPA", "Cost")

ggplot(chunk3_data, aes(x = Cost, y = CPA, size = Conversions)) +
    geom_point() +
    geom_text(aes(label = Campaign))

```

## Performance: Last 90 days

```{r campaign scatterplot 4, echo=FALSE, eval=FALSE, eval=FALSE}

ninetyDaysAgo <- today() - days(90)

chunk4_body <- statement(select=c('CampaignName','Conversions','CostPerConversion','Cost'),
                         report="CAMPAIGN_PERFORMANCE_REPORT",
                         where="Cost > 150000000",
                         start=ninetyDaysAgo,
                         end=yesterday)

chunk4_data <- getData(clientCustomerId=customerId, google_auth=googleAuth, statement=chunk4_body)

names(chunk4_data) <- c("Campaign", "Conversions", "CPA", "Cost")

 ggplot(chunk4_data, aes(x = Cost, y = CPA, size = Conversions)) +
    geom_point() +
    geom_text(aes(label = Campaign))

```

# Metrics correlation plot

```{r correlation plot, echo=FALSE, eval=FALSE}

aYearAgo <- today() - days(365)

chunk5_body <- statement(select=c('Date','Clicks','Conversions','CostPerConversion',
                                  'Cost','ConversionRate','AverageCpc','Impressions','Ctr'),
                         report="ACCOUNT_PERFORMANCE_REPORT",
                         start=aYearAgo,
                         end=yesterday)

chunk5_data <- getData(clientCustomerId=customerId, google_auth=googleAuth, statement=chunk5_body)

corr <- cor(chunk5_data[,-1])

corrplot(corr, method = "pie", type = "upper")

```		
# Ad Scheduling Heatmaps

## Ad Scheduling: Impressions

```{r ad scheduling heatmap 1, echo=FALSE, eval=FALSE}

ninetyDaysAgo <- today() - days(90)

chunk6_body <- statement(select=c("DayOfWeek","HourOfDay","Impressions","Conversions","CostPerConversion","SearchImpressionShare"),
                         report="ACCOUNT_PERFORMANCE_REPORT",
                         start=ninetyDaysAgo,
                         end=yesterday)

chunk6_data <- getData(clientCustomerId=customerId, google_auth=googleAuth, statement=chunk6_body)

names(chunk6_data) <- c("DayOfWeek", "HourOfDay", "Impressions", "Conversions","CPA","SearchIS")

chunk6_data$HourOfDay <- factor(chunk6_data$HourOfDay, levels=c(0:23))
chunk6_data$DayOfWeek <- factor(chunk6_data$DayOfWeek, levels=c("Sunday","Saturday","Friday","Thursday","Wednesday","Tuesday","Monday"))

ggplot(chunk6_data, aes(x=HourOfDay, y=DayOfWeek, z=Impressions)) + geom_tile(aes(fill = Impressions)) +
    scale_fill_gradient(low="white", high="blue", labels=comma)

```

## Ad Scheduling: Search Impression Share

```{r ad scheduling heatmap 2, echo=FALSE, eval=FALSE}

ggplot(chunk6_data, aes(x=HourOfDay, y=DayOfWeek, z=SearchIS)) + geom_tile(aes(fill = SearchIS)) +
    scale_fill_gradient2(low="white", high="blue", labels=comma, midpoint=0.5)

```

## Ad Scheduling: Conversions

```{r ad scheduling heatmap 3, echo=FALSE, eval=FALSE}

ggplot(chunk6_data, aes(x=HourOfDay, y=DayOfWeek, z=Conversions)) + geom_tile(aes(fill = Conversions)) +
    scale_fill_gradient(low="white", high="blue", labels=comma)

```

## Ad Scheduling: CPA

```{r ad scheduling heatmap 4, echo=FALSE, eval=FALSE}

ggplot(chunk6_data[chunk6_data$CPA > 0,], aes(x=HourOfDay, y=DayOfWeek, z=CPA)) + geom_tile(aes(fill = CPA)) +
    scale_fill_gradient2(low="white", high="blue", labels=comma, midpoint=50)

```
